# Generated by Django 4.1.4 on 2022-12-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('model', models.CharField(choices=[('text-davinci-003', 'text-davinci-003'), ('text-curie-001', 'text-curie-001'), ('code-davinci-002', 'code-davinci-002')], default='AUT', max_length=300)),
                ('answer', models.TextField(verbose_name='response from open ai')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
