# Generated by Django 4.1.4 on 2023-01-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_openaiplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiplay',
            name='category',
            field=models.CharField(choices=[('Q&A', 'Q&A'), ('Summarize for a 2nd grader', 'Summarize for a 2nd grader'), ('Text to command', 'Text to command'), ('Keywords', 'Keywords')], default='Q&A', max_length=300),
        ),
        migrations.AlterField(
            model_name='openaiplay',
            name='model',
            field=models.CharField(choices=[('text-davinci-003', 'text-davinci-003'), ('text-curie-001', 'text-curie-001'), ('code-davinci-002', 'code-davinci-002')], default='text-davinci-003', max_length=300),
        ),
    ]
