# Generated by Django 4.1.4 on 2023-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_openaiplay_category_alter_openaiplay_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiplay',
            name='full_response',
            field=models.TextField(default='', help_text='response from open ai'),
        ),
        migrations.AlterField(
            model_name='openaiplay',
            name='answer',
            field=models.TextField(default='', help_text='text from open ai'),
        ),
    ]
