# Generated by Django 4.1.4 on 2023-01-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_openaiplay_full_response_alter_openaiplay_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='openaiplay',
            name='category',
            field=models.CharField(choices=[('Q&A', 'Q&A'), ('Summarize for a 2nd grader', 'Summarize for a 2nd grader'), ('Text to command', 'Text to command'), ('Keywords', 'Keywords'), ('Code', 'Code Generation')], default='Q&A', max_length=300),
        ),
    ]
